package service

import (
	"context"
	"errors"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/fpbcraft/fpbcraft/tools/fpbpack/internal/catalog"
	"github.com/fpbcraft/fpbcraft/tools/fpbpack/internal/inventory"
	updates "github.com/fpbcraft/fpbcraft/tools/fpbpack/internal/updates"
)

func TestNewBootstrapsWithoutBlockingOnGeneratedCaches(t *testing.T) {
	root := t.TempDir()
	stateDir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mods"), 0o755); err != nil {
		t.Fatal(err)
	}

	service, err := New(context.Background(), Options{
		ServerRoot: root,
		StateDir:   stateDir,
	})
	if err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(stateDir, "state.json")); err != nil {
		t.Fatalf("state.json was not generated: %v", err)
	}
	for _, name := range []string{"inventory.json", "updates.json"} {
		if _, err := os.Stat(filepath.Join(stateDir, name)); !os.IsNotExist(err) {
			t.Fatalf("%s should not be generated by New", name)
		}
	}
	if err := service.Refresh(context.Background()); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"inventory.json", "updates.json"} {
		if _, err := os.Stat(filepath.Join(stateDir, name)); err != nil {
			t.Fatalf("%s was not generated by Refresh: %v", name, err)
		}
	}
	snapshot, err := service.Snapshot()
	if err != nil {
		t.Fatal(err)
	}
	if snapshot.Status.Mods != 0 {
		t.Fatalf("mods = %d, want 0", snapshot.Status.Mods)
	}
	if _, err := service.Updates(); err != nil {
		t.Fatalf("updates not ready: %v", err)
	}
}

func TestNewImportsLegacyReportOnlyWhenStateIsMissing(t *testing.T) {
	root := t.TempDir()
	stateDir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mods"), 0o755); err != nil {
		t.Fatal(err)
	}

	report := catalog.Report{
		SchemaVersion: catalog.ReportSchemaVersion,
		Pinned: []catalog.PinnedArtifact{{
			SHA512: "legacy",
			Filename: "custom.jar",
			Reason: "legacy unmanaged artifact",
		}},
	}
	report.Summary.PinnedArtifacts = 1
	bytes, err := json.Marshal(report)
	if err != nil {
		t.Fatal(err)
	}
	legacyPath := filepath.Join(stateDir, "migration-report.json")
	if err := os.WriteFile(legacyPath, bytes, 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := New(context.Background(), Options{ServerRoot: root, StateDir: stateDir}); err != nil {
		t.Fatal(err)
	}

	var state State
	stateBytes, err := os.ReadFile(filepath.Join(stateDir, "state.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(stateBytes, &state); err != nil {
		t.Fatal(err)
	}
	if state.ImportedFrom == "" {
		t.Fatal("expected imported_from to record legacy bootstrap")
	}
	if len(state.Catalog.Pinned) != 1 {
		t.Fatalf("pinned = %d, want 1", len(state.Catalog.Pinned))
	}
}

func TestNewLoadsRuntimeCachesWithoutRefreshing(t *testing.T) {
	root := t.TempDir()
	stateDir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mods"), 0o755); err != nil {
		t.Fatal(err)
	}

	now := time.Now().UTC()
	state := State{
		SchemaVersion: StateSchemaVersion,
		CreatedAt: now,
		UpdatedAt: now,
		Settings: RuntimeSettings{RetentionCount: DefaultRetentionCount},
		Catalog: catalog.Report{SchemaVersion: catalog.ReportSchemaVersion},
	}
	if err := writeJSONAtomic(filepath.Join(stateDir, "state.json"), state); err != nil {
		t.Fatal(err)
	}
	inv := inventory.Inventory{
		SchemaVersion: inventory.SchemaVersion,
		GeneratedAt: now,
		ServerRoot: root,
		ServerModsPath: "mods",
		ClientModsPath: inventory.DefaultClientModsPath,
	}
	if err := writeJSONAtomic(filepath.Join(stateDir, "inventory.json"), inv); err != nil {
		t.Fatal(err)
	}
	report := updates.Report{
		GeneratedAt: now,
		Minecraft: "1.21.1",
		Loader: "neoforge",
	}
	if err := writeJSONAtomic(filepath.Join(stateDir, "updates.json"), report); err != nil {
		t.Fatal(err)
	}

	service, err := New(context.Background(), Options{ServerRoot: root, StateDir: stateDir})
	if err != nil {
		t.Fatal(err)
	}
	snapshot, err := service.Snapshot()
	if err != nil {
		t.Fatal(err)
	}
	if !snapshot.Inventory.GeneratedAt.Equal(now) {
		t.Fatalf("cached inventory was not loaded")
	}
	gotUpdates, err := service.Updates()
	if err != nil {
		t.Fatal(err)
	}
	if !gotUpdates.GeneratedAt.Equal(now) {
		t.Fatalf("cached updates were not loaded")
	}
}

func TestCancelledUpdateDiscoveryDoesNotReplaceLastGoodCache(t *testing.T) {
	stateDir := t.TempDir()
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mods"), 0o755); err != nil {
		t.Fatal(err)
	}

	now := time.Now().UTC()
	lastGood := updates.Report{
		GeneratedAt: now,
		Minecraft: "1.21.1",
		Loader: "neoforge",
	}
	if err := writeJSONAtomic(filepath.Join(stateDir, "updates.json"), lastGood); err != nil {
		t.Fatal(err)
	}

	svc := &Service{
		options: Options{
			ServerRoot: root,
			StateDir: stateDir,
			Minecraft: "1.21.1",
			Loader: "neoforge",
		},
		state: State{
			SchemaVersion: StateSchemaVersion,
			Settings: RuntimeSettings{RetentionCount: DefaultRetentionCount},
			Catalog: catalog.Report{SchemaVersion: catalog.ReportSchemaVersion},
		},
		updates: lastGood,
		hasUpdate: true,
	}

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	err := svc.CheckUpdates(ctx)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("CheckUpdates error = %v, want context.Canceled", err)
	}

	var persisted updates.Report
	if err := readJSON(filepath.Join(stateDir, "updates.json"), &persisted); err != nil {
		t.Fatal(err)
	}
	if !persisted.GeneratedAt.Equal(lastGood.GeneratedAt) {
		t.Fatalf("cancelled discovery replaced last good cache")
	}
}
