package service

import (
	"context"
	"errors"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/fpbcraft/fpbcraft/tools/fpbpack/internal/catalog"
	"github.com/fpbcraft/fpbcraft/tools/fpbpack/internal/inventory"
	updates "github.com/fpbcraft/fpbcraft/tools/fpbpack/internal/updates"
)

func TestNewBootstrapsWithoutBlockingOnGeneratedCaches(t *testing.T) {
	root := t.TempDir()
	stateDir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mods"), 0o755); err != nil {
		t.Fatal(err)
	}

	service, err := New(context.Background(), Options{
		ServerRoot: root,
		StateDir:   stateDir,
	})
	if err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(stateDir, "state.json")); err != nil {
		t.Fatalf("state.json was not generated: %v", err)
	}
	for _, name := range []string{"inventory.json", "updates.json"} {
		if _, err := os.Stat(filepath.Join(stateDir, name)); !os.IsNotExist(err) {
			t.Fatalf("%s should not be generated by New", name)
		}
	}
	if err := service.Refresh(context.Background()); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"inventory.json", "updates.json"} {
		if _, err := os.Stat(filepath.Join(stateDir, name)); err != nil {
			t.Fatalf("%s was not generated by Refresh: %v", name, err)
		}
	}
	snapshot, err := service.Snapshot()
	if err != nil {
		t.Fatal(err)
	}
	if snapshot.Status.Mods != 0 {
		t.Fatalf("mods = %d, want 0", snapshot.Status.Mods)
	}
	if _, err := service.Updates(); err != nil {
		t.Fatalf("updates not ready: %v", err)
	}
}

func TestNewImportsLegacyReportOnlyWhenStateIsMissing(t *testing.T) {
	root := t.TempDir()
	stateDir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mods"), 0o755); err != nil {
		t.Fatal(err)
	}

	report := catalog.Report{
		SchemaVersion: catalog.ReportSchemaVersion,
		Pinned: []catalog.PinnedArtifact{{
			SHA512: "legacy",
			Filename: "custom.jar",
			Reason: "legacy unmanaged artifact",
		}},
	}
	report.Summary.PinnedArtifacts = 1
	bytes, err := json.Marshal(report)
	if err != nil {
		t.Fatal(err)
	}
	legacyPath := filepath.Join(stateDir, "migration-report.json")
	if err := os.WriteFile(legacyPath, bytes, 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := New(context.Background(), Options{ServerRoot: root, StateDir: stateDir}); err != nil {
		t.Fatal(err)
	}

	var state State
	stateBytes, err := os.ReadFile(filepath.Join(stateDir, "state.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(stateBytes, &state); err != nil {
		t.Fatal(err)
	}
	if state.ImportedFrom == "" {
		t.Fatal("expected imported_from to record legacy bootstrap")
	}
	if len(state.Catalog.Pinned) != 1 {
		t.Fatalf("pinned = %d, want 1", len(state.Catalog.Pinned))
	}
}

func TestNewLoadsRuntimeCachesWithoutRefreshing(t *testing.T) {
	root := t.TempDir()
	stateDir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mods"), 0o755); err != nil {
		t.Fatal(err)
	}

	now := time.Now().UTC()
	state := State{
		SchemaVersion: StateSchemaVersion,
		CreatedAt: now,
		UpdatedAt: now,
		Settings: RuntimeSettings{RetentionCount: DefaultRetentionCount},
		Catalog: catalog.Report{SchemaVersion: catalog.ReportSchemaVersion},
	}
	if err := writeJSONAtomic(filepath.Join(stateDir, "state.json"), state); err != nil {
		t.Fatal(err)
	}
	inv := inventory.Inventory{
		SchemaVersion: inventory.SchemaVersion,
		GeneratedAt: now,
		ServerRoot: root,
		ServerModsPath: "mods",
		ClientModsPath: inventory.DefaultClientModsPath,
	}
	if err := writeJSONAtomic(filepath.Join(stateDir, "inventory.json"), inv); err != nil {
		t.Fatal(err)
	}
	report := updates.Report{
		GeneratedAt: now,
		Minecraft: "1.21.1",
		Loader: "neoforge",
	}
	if err := writeJSONAtomic(filepath.Join(stateDir, "updates.json"), report); err != nil {
		t.Fatal(err)
	}

	service, err := New(context.Background(), Options{ServerRoot: root, StateDir: stateDir})
	if err != nil {
		t.Fatal(err)
	}
	snapshot, err := service.Snapshot()
	if err != nil {
		t.Fatal(err)
	}
	if !snapshot.Inventory.GeneratedAt.Equal(now) {
		t.Fatalf("cached inventory was not loaded")
	}
	gotUpdates, err := service.Updates()
	if err != nil {
		t.Fatal(err)
	}
	if !gotUpdates.GeneratedAt.Equal(now) {
		t.Fatalf("cached updates were not loaded")
	}
}

func TestCancelledUpdateDiscoveryDoesNotReplaceLastGoodCache(t *testing.T) {
	stateDir := t.TempDir()
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mods"), 0o755); err != nil {
		t.Fatal(err)
	}

	now := time.Now().UTC()
	lastGood := updates.Report{
		GeneratedAt: now,
		Minecraft: "1.21.1",
		Loader: "neoforge",
	}
	if err := writeJSONAtomic(filepath.Join(stateDir, "updates.json"), lastGood); err != nil {
		t.Fatal(err)
	}

	svc := &Service{
		options: Options{
			ServerRoot: root,
			StateDir: stateDir,
			Minecraft: "1.21.1",
			Loader: "neoforge",
		},
		state: State{
			SchemaVersion: StateSchemaVersion,
			Settings: RuntimeSettings{RetentionCount: DefaultRetentionCount},
			Catalog: catalog.Report{SchemaVersion: catalog.ReportSchemaVersion},
		},
		updates: lastGood,
		hasUpdate: true,
	}

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	err := svc.CheckUpdates(ctx)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("CheckUpdates error = %v, want context.Canceled", err)
	}

	var persisted updates.Report
	if err := readJSON(filepath.Join(stateDir, "updates.json"), &persisted); err != nil {
		t.Fatal(err)
	}
	if !persisted.GeneratedAt.Equal(lastGood.GeneratedAt) {
		t.Fatalf("cancelled discovery replaced last good cache")
	}
}


func TestAutoModpackConfigUsesOptimisticConcurrencyAndBackups(t *testing.T) {
	root := t.TempDir()
	stateDir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mods"), 0o755); err != nil {
		t.Fatal(err)
	}
	configDir := filepath.Join(root, "automodpack")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatal(err)
	}
	config := `modpack-host: true
bandwidth-limit: 0
future-setting: "preserve-me"
modpack {
  name: "FPBCraft"
  General {
    main {
      required: true
      default-selected: true
      from-server: ["mods/*.jar"]
      future-group-setting: "preserve-me-too"
    }
  }
}
`
	if err := os.WriteFile(filepath.Join(configDir, "server.conf"), []byte(config), 0o644); err != nil {
		t.Fatal(err)
	}

	svc, err := New(context.Background(), Options{ServerRoot: root, StateDir: stateDir})
	if err != nil {
		t.Fatal(err)
	}
	status, err := svc.AutoModpackStatus()
	if err != nil {
		t.Fatal(err)
	}
	if !status.ConfigPresent || status.ConfigSHA256 == "" {
		t.Fatalf("unexpected status: %+v", status)
	}
	next := status.Config
	next.Settings.BandwidthLimit = 42
	updated, err := svc.UpdateAutoModpackConfig(context.Background(), AutoModpackConfigRequest{
		ExpectedSHA256: status.ConfigSHA256,
		Config: next,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !updated.PendingPublish {
		t.Fatal("config update should mark AutoModpack publication pending")
	}
	written, err := os.ReadFile(filepath.Join(configDir, "server.conf"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(written), "bandwidth-limit: 42") ||
		!strings.Contains(string(written), "future-setting") ||
		!strings.Contains(string(written), "future-group-setting") {
		t.Fatalf("saved config lost expected content:\n%s", string(written))
	}
	backups, err := os.ReadDir(filepath.Join(stateDir, "automodpack", "config-backups"))
	if err != nil {
		t.Fatal(err)
	}
	if len(backups) != 1 {
		t.Fatalf("config backups = %d, want 1", len(backups))
	}
	if _, err := svc.UpdateAutoModpackConfig(context.Background(), AutoModpackConfigRequest{
		ExpectedSHA256: status.ConfigSHA256,
		Config: next,
	}); err == nil {
		t.Fatal("stale config hash should be rejected")
	}
}

func TestAutoModpackStatusReadsGenerationJournal(t *testing.T) {
	root := t.TempDir()
	stateDir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "mods"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "automodpack", "server"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "automodpack"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(
		filepath.Join(root, "automodpack", "server.conf"),
		[]byte(`modpack { name: "FPBCraft" General { main { required: true } } }`),
		0o644,
	); err != nil {
		t.Fatal(err)
	}
	journal := `{"seq":1,"contentToken":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","policySha1":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","createdAt":"2026-10-06T01:00:00Z","notes":"Initial","restoreOf":-1,"changes":[{"path":"mods/a.jar","fromSha1":null,"fromSize":0,"toSha1":"cccccccccccccccccccccccccccccccccccccccc","toSize":123}]}
{"seq":2,"contentToken":"dddddddddddddddddddddddddddddddddddddddd","policySha1":"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee","createdAt":"2026-10-06T02:00:00Z","notes":"Update","restoreOf":-1,"changes":[{"path":"mods/a.jar","fromSha1":"cccccccccccccccccccccccccccccccccccccccc","fromSize":123,"toSha1":"ffffffffffffffffffffffffffffffffffffffff","toSize":125},{"path":"config/x","fromSha1":null,"fromSize":0,"toSha1":"1111111111111111111111111111111111111111","toSize":5}]}
`
	if err := os.WriteFile(filepath.Join(root, "automodpack", "server", "journal.jsonl"), []byte(journal), 0o644); err != nil {
		t.Fatal(err)
	}
	svc, err := New(context.Background(), Options{ServerRoot: root, StateDir: stateDir})
	if err != nil {
		t.Fatal(err)
	}
	status, err := svc.AutoModpackStatus()
	if err != nil {
		t.Fatal(err)
	}
	if len(status.Generations) != 2 || status.Generations[0].Sequence != 2 {
		t.Fatalf("unexpected generation history: %+v", status.Generations)
	}
	if status.Generations[0].Summary.Added != 1 || status.Generations[0].Summary.Changed != 1 {
		t.Fatalf("unexpected generation summary: %+v", status.Generations[0].Summary)
	}
}
